sudo: false

os:
  - linux

env:
  - RAILS_ENV=test ELM_VERSION=0.18.0 ELM_CSS_VERSION=0.6.1

cache:
  directories:
    - $TRAVIS_BUILD_DIR/client/elm-stuff/build-artifacts

before_install:
  - echo "Install elm-lang and elm-css"
  - echo "elm version = $ELM_VERSION"
  - echo "elm css version = $ELM_CSS_VERSION"
  - cd $TRAVIS_BUILD_DIR/client
  - npm install -g elm@$ELM_VERSION elm-css@$ELM_CSS_VERSION
  - cd $TRAVIS_BUILD_DIR

install:
  - echo "Install restbus (ruby on rails)"
  - cd $TRAVIS_BUILD_DIR/restbus
  - make install
  - echo "Install client (elm)"
  - cd $TRAVIS_BUILD_DIR/client
  - make install

script:
  - echo "test restbus (ruby on rails)"
  - cd $TRAVIS_BUILD_DIR/restbus
  - bundle exec rspec test


