sudo: false

os:
  - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/client/elm-stuff/build-artifacts

env:
  global:
    - GOOGLE_MAPS_API=AIzaSyCrvF3M7oX7JEY74mo6hfpu3rgHdwuNIrw
    - ELM_VERSION=0.18.0
    - ELM_CSS_VERSION=0.6.1

jobs:
  include:
    - stage: test
      env:
        - RAILS_ENV=test
      bundler_args:
        --without production
      before_install:
        - echo "Install elm-lang and elm-css"
        - echo "elm version = $ELM_VERSION"
        - echo "elm css version = $ELM_CSS_VERSION"
        - npm install -g elm@$ELM_VERSION elm-css@$ELM_CSS_VERSION
      install:
        - cd $TRAVIS_BUILD_DIR
        - echo "Install restbus (ruby on rails)"
        - cd $TRAVIS_BUILD_DIR/restbus
        - make install
        - echo "Install client (elm)"
        - cd $TRAVIS_BUILD_DIR/client
        - make install
      script:
        - echo "test restbus (ruby on rails)"
        - cd $TRAVIS_BUILD_DIR/restbus
        - bin/rspec
    - stage: deploy
      env:
        - RAILS_ENV=production
      bundler_args:
        --without development,test
      before_install:
        - echo "Install elm-lang and elm-css"
        - echo "elm version = $ELM_VERSION"
        - echo "elm css version = $ELM_CSS_VERSION"
        - npm install -g elm@$ELM_VERSION elm-css@$ELM_CSS_VERSION
      install:
        - cd $TRAVIS_BUILD_DIR
        - echo "Install restbus (ruby on rails)"
        - cd $TRAVIS_BUILD_DIR/restbus
        - make install
        - echo "Install client (elm)"
        - cd $TRAVIS_BUILD_DIR/client
        - make install
      script: skip
    - stage: seedee
      install:
        - echo "Installing Chef DK"
        - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk
        - echo "Installed Chef DK"
      script: skip


stages:
  # - test
  # - deploy
  - seedee
