sudo: false

os:
  - linux

env:
  matrix:
    - ELM_VERSION: 0.18.0
    - ELM_CSS_VERSION: 0.6.1



cache:
  directories:
    client/elm-stuff/build-artifacts

before_install:
  - echo "Install elm-lang and elm-css"
  - cd client
  - npm install -g elm@ELM_VERSION elm-css@ELM_CSS_VERSION

install:
  - echo "Install client (elm) and restbus (ruby on rails)"
  - make install
