sudo: false

os:
  - linux

env:
  - ELM_VERSION=0.18.0
  - ELM_CSS_VERSION=0.6.1

cache:
  directories:
    client/elm-stuff/build-artifacts

before_install:
  - echo "Install elm-lang and elm-css"
  - cd client
  - echo "elm version = $ELM_VERSION"
  - echo "elm css version = $ELM_CSS_VERSION"
  - npm install -g elm@$ELM_VERSION elm-css@$ELM_CSS_VERSION
  - cd ..

install:
  - echo "Install restbus (ruby on rails)"
  - cd restbus
  - make install
  - echo "Install client (elm)"
  - cd ../client
  - make install
