source 'https://rubygems.org'

gem 'rails', '4.2.10'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Twitter client
gem 'twitter'

gem 'active_model_serializers'

# Application server
gem 'puma'

# Internet gems
gem 'rest-client'
gem 'nokogiri'

gem 'google-api-client'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'awesome_print'

  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'guard'
  gem 'guard-rspec', require: false

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'

  gem 'factory_girl_rails', '~> 4.0'
  gem 'database_cleaner'

  # Database server (PostgreSQL)
  gem 'pg'
end

group :production do
  gem 'clockwork'
  gem 'daemons'

  # Database server (PostgreSQL)
  gem 'pg'
end
