module Ttc
  module Train
    STATIONS = {
      'Vaughan Metropolitan Centre' => 80,
      'Highway 407' => 79,
      'Pioneer Village' => 78,
      'York University' => 77,
      'Finch West' => 76,
      'Downsview Park' => 75,
      'Sheppard West' => 1,
      'Wilson' => 2,
      'Yorkdale' => 3,
      'Lawrence West' => 4,
      'Glencairn' => 5,
      'Eglinton West' => 6,
      'St. Clair West' => 7,
      'Dupont' => 8,
      'Spadina' => 9,
      'St. George' => 10,
      'Museum' => 11,
      'Queen\'s Park' => 12,
      'St. Patrick' => 13,
      'Osgoode' => 14,
      'St. Andrew' => 15,
      'Union' => 16,
      'King' => 17,
      'Queen' => 18,
      'Dundas' => 19,
      'College' => 20,
      'Wellesley' => 21,
      'Bloor-Yonge' => 22,
      'Rosedale' => 23,
      'Summerhill' => 24,
      'St. Clair' => 25,
      'Davisville' => 26,
      'Eglinton' => 27,
      'Lawrence' => 28,
      'York mills' => 29,
      'Sheppard-Yonge' => 30,
      'North York Centre' => 31,
      'Finch' => 78
    }.freeze
  end
end
