source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.10'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'geocoder'
gem 'rest-client'
gem 'puma'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'awesome_print'

  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-its'
  gem 'guard'
  gem 'guard-rspec', require: false

  gem 'factory_girl_rails', '~> 4.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
end
